version: '2.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test-db
    ports:
      - "3306:3306"
  ##sv-dr:
  ##  build: ./services/DataRetrieval
  ##  ports:
  ##    - "8081:80"
  ##sv-ad:
  ##  build: ./services/DataAnalytics
  ##  ports:
  ##    - "8082:80"
  sv-email:
    build: ./services/Email
    ports:
      - "8083:80"