version: '2.1'

services:
  krakend:
    build: ./api-gateway
    ports:
      - "80:8080"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test-db
    volumes:
      - ./:/docker-entrypoint-initdb.d
    ports:
      - "3306"
    container_name: db
  rabbitmq:
    image: rabbitmq:3-alpine
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    expose:
      - "5672"
    container_name: rabbitmq
  sv-producer:
    build: ./producer
    ports:
      - '80'
    depends_on:
      - rabbitmq
  sv-consumer:
    build: ./consumer
    ports:
      - '80'
    depends_on:
      - db
  sv-data-analytics:
    build: ./services/DataAnalytics
    ports:
      - '80'
    depends_on:
      - db
  sv-data-retrieval:
    build: ./services/DataRetrieval
    ports:
      - '80'
    depends_on:
      - db
  sv-email:
    build: ./services/Email
    ports:
      - '80'
  sv-jwt:
    build: ./jwt
    ports:
      - '8080:8080'
    depends_on:
      - db